### ISSUE TITLE
Does `watch [files]` actual watch files?

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/cli#19]
The `_files` parameter does not appear to be used:

https://github.com/theintern/cli/blob/5503a27c6274d43200e091c0e39d8bf688300f76/src/lib/cli4.ts#L308..L353

**Comment by gitgrimbo** [comment]
The watch parameter doesn't seem to work at all on Windows.  You get one pass of the tests, then the command prompt waits, and changing and saving files does not trigger a re-run of the tests.

And Ctrl+C does not kill the process, so the command prompt hangs.

**Comment by jason0x43** [comment]
Closing this since watch functionality will be more of a focus with the next major update to Intern (theintern/intern#1020).
