### ISSUE TITLE
proxyOnly isn't a thing anymore

### ISSUE THREAD

**Issue by sholladay** [theintern/cli#3]
This looks like [refactoring cruft](https://github.com/theintern/intern-cli/blob/df05b3c65e9524fec2399178a518e0b3779ad749/bin/intern.js#L258) left over from the older `intern-runner` CLI.

Presumably `intern serve` is a proper replacement for this?

I did try it out of curiosity and it erroneously went ahead and ran the tests.

**Comment by jason0x43** [comment]
Closing this as the current CLI code no longer has references to `proxyOnly`.
