### ISSUE TITLE
Prefer --webdriver use case

### ISSUE THREAD

**Issue by sholladay** [theintern/cli#5]
Two independent but related ideas here, to make Intern more friendly for browser tests.

Rename `--webdriver` to `--browser`. It is shorter to type, `intern run --browser` looks very nice and intuitive. Also, I think the complexity and reputation of Selenium / WebDriver can be a turn off for people. Much of Intern's life has been dedicated to abstracting and simplifying everything around WebDriver. With the introduction of SeleniumTunnel, I think we are to a point where most people won't have to worry too much about what is being used under the hood. And this could help make it easier to understand what `functionalSuites`[are for](https://github.com/theintern/intern/issues/669#issuecomment-246802550).

Default to `--webdriver`. I think this feature is _why_ people come to Intern, instead of Mocha and friends. Also, if you think about the types of tests that can be run (Node unit, browser unit, functional), this mode is required for 2/3 of them. I think it's awesome that Intern can run Node tests, but with its preference for AMD, most Intern users are almost certainly browser-based projects. Even if we assume it is 50/50, `--node` is shorter to type. This would be even better if `SeleniumTunnel` were the default `tunnel`.

**Comment by devpaul** [comment]
Just wanted to mention that webdriver refers to the protocol and while I'm sure there's few, if any, people using Appium over webdriver to test native mobile applications, it can technically be used for such.

Regarding your second point, how do you feel about a `.intern` config file in the project or home directory to configure default behaviors? How do you and your team feel about using `npm scripts` or other task runner instead for this configuration?

**Comment by sholladay** [comment]
> people using Appium

I did think about about that. It's true and the docs do specifically call out that you can test native apps, etc. I figure that those people will be used to weird incantations, but I agree that may be a step backward for those people. However, it doesn't have to be if it becomes the default!

> how do you feel about a .intern config file in the project or home directory to configure default behaviors?

I don't think another config file will solve anything. Being able to specify the `runType` in the `intern.js` config like you can in the Grunt task would be interesting, I guess. But that wouldn't have the same impact as what I am proposing here.

> How do you and your team feel about using npm scripts or other task runner instead for this configuration?

For the common cases, we do have `npm` scripts. However, I find that in practice people work up their own special commands to fit their workflow at any given time. Sometimes it's as simple as a special set of `suites` or `reporters`. And because of this they often fallback to using the `intern` command themselves instead of the pre-made scripts.

**Comment by jason0x43** [comment]
Closing this as Intern no longer exposes separate node and webdriver runners from the command line.
