### ISSUE TITLE
Update intern-cli for Intern 4

### ISSUE THREAD

**Issue by morrinene** [theintern/cli#7]
As part of the ES6/TS refactor, we are migrating the CLI to TypeScript and updating it for Intern 4.  This issue will cover the conversion and test updates needed.

Be sure to take into consideration work done for the Intern Migration: theintern/intern#674

**Comment by jason0x43** [comment]
The CLI was migrated to TS some time ago (thanks, @nicknisi!), so the main goal now is really to get it working with Intern 4. Basic support was added in commit 0f25d736410f0139d23b61ebdc9a1485e5ef1145. Now if I can just remember to start referencing this issue...

**Comment by jason0x43** [comment]
The initial update was finished in 9c3a999b51517e35fa1117bad873e2872ba3b6f2.
